feat: can configure other keyboard with a layout (fr, us)

diff --git a/bin/toggle-dual-keyboard-layout b/bin/toggle-dual-keyboard-layout
--- a/bin/toggle-dual-keyboard-layout
+++ b/bin/toggle-dual-keyboard-layout
@@ -1,4 +1,5 @@
 #!/bin/bash
+
 #
 # Enable other standard keyboards along a connected TypeMatrix.
 #
@@ -7,30 +8,51 @@
 
 set -euo pipefail
 
-readonly TYPEMATRIX_KEYBOARDS=$(xinput list |
-  grep keyboard |
-  grep TypeMatrix |
-  sed 's/.*id=\([0-9]*\).*/\1/')
+function usage() {
+  local SCRIPT
+  SCRIPT="$(basename "$0")"
+  echo "Usage: $SCRIPT layout"
+  echo "Example: $SCRIPT fr"
+}
 
-readonly OTHER_KEYBOARDS=$(xinput list |
-  grep -i 'keyboard.*id=.*slave.*keyboard' |
-  grep -vE '(TypeMatrix|XTEST|AT Translated)' |
-  sed 's/.*id=\([0-9]*\).*/\1/')
+function toggle() {
+  local LAYOUT="$1"
 
-if [[ -n "$OTHER_KEYBOARDS" ]]; then
-  for keyboard in $OTHER_KEYBOARDS; do
-    setxkbmap -device "$keyboard" fr -option ""
-  done
-  notify-send -i "input-keyboard" "Success" "Azerty keyboard enabled"
+  readonly TYPEMATRIX_KEYBOARDS=$(xinput list |
+    grep keyboard |
+    grep TypeMatrix |
+    sed 's/.*id=\([0-9]*\).*/\1/')
+
+  readonly OTHER_KEYBOARDS=$(xinput list |
+    grep -i 'keyboard.*id=.*slave.*keyboard' |
+    grep -vE '(TypeMatrix|XTEST|AT Translated)' |
+    sed 's/.*id=\([0-9]*\).*/\1/')
+
+  if [[ -n "$OTHER_KEYBOARDS" ]]; then
+    for keyboard in $OTHER_KEYBOARDS; do
+      setxkbmap -device "$keyboard" "$LAYOUT" -option ""
+    done
+    notify-send -i "input-keyboard" "Success" "Other keyboard configured as $LAYOUT"
+  else
+    notify-send -i "error" "Error" "Other keyboard NOT CONFIGURED"
+  fi
+
+  if [[ -n "$TYPEMATRIX_KEYBOARDS" ]]; then
+    for keyboard in $TYPEMATRIX_KEYBOARDS; do
+      setxkbmap -device "$keyboard" us -variant colemak
+    done
+    notify-send -i "input-keyboard" "Success" "Typematrix keyboard configured"
+  else
+    notify-send -i "error" "Error" "Typematrix keyboard NOT CONFIGURED"
+  fi
+}
+
+set +u
+if [ -z "$1" ]; then
+  echo "Missing layout param"
+  usage
+  exit 1
 else
-  notify-send -i "error" "Error" "Standard keyboard NOT ENABLED"
+  toggle "$1"
 fi
-
-if [[ -n "$TYPEMATRIX_KEYBOARDS" ]]; then
-  for keyboard in $TYPEMATRIX_KEYBOARDS; do
-    setxkbmap -device "$keyboard" us -variant colemak
-  done
-  notify-send -i "input-keyboard" "Success" "Typematrix keyboard enabled"
-else
-  notify-send -i "error" "Error" "Typematrix keyboard NOT ENABLED"
-fi
+set -u
