move functions to their own dir + simpler rake completion

diff --git a/zsh/functions/alert b/zsh/functions/alert
--- a/zsh/functions/alert
+++ b/zsh/functions/alert
@@ -1,8 +1,10 @@
-local exitstatus="$?"
-if [[ $exitstatus = "0" ]]; then
-  /usr/bin/notify-send -i "terminal" "Success" "Last command exited successfully"
-  /usr/bin/beep -l 10 -f 5000 -r 1
-else
-  /usr/bin/notify-send -i "error" "Error" "Last script exited with status $exitstatus"
-  /usr/bin/beep -l 100 -f 10 -r 1
-fi
+function alert() {
+  local exitstatus="$?"
+  if [[ $exitstatus = "0" ]]; then
+    /usr/bin/notify-send -i "terminal" "Success" "Last command exited successfully"
+    /usr/bin/beep -l 10 -f 5000 -r 1
+  else
+    /usr/bin/notify-send -i "error" "Error" "Last script exited with status $exitstatus"
+    /usr/bin/beep -l 100 -f 10 -r 1
+  fi
+}
